Repository yoonms0617/together, pull requests merged in 2023-03, with the labels that each got.

#11 PlaceVO 추가
  project/src/main/java/com/sist/vo/PlaceVO.java
Labels: ✨ 기능

#13 베스트팁 , 리뷰모음 VO 추가
  project/src/main/java/com/sist/vo/BestTipVO.java
  project/src/main/java/com/sist/vo/ReviewVO.java
Labels: ✨ 기능

#14 vo추가
  project/src/main/java/com/sist/vo/CommunityVO.java
Labels: ✨ 기능

#17 송상은 vo추가
  project/src/main/java/com/sist/vo/CommunityReplyVO.java
  project/src/main/java/com/sist/vo/NoticeVO.java
Labels: ✨ 기능

#22 로그인 및 회원가입 페이지 추가
  project/src/main/webapp/resources/templates/member/login.jsp
  project/src/main/webapp/resources/templates/member/signup.jsp
Labels: 🖥️ UI

#24 전역 예외처리 기능 구현
  project/src/main/java/com/sist/global/error/GlobalExceptionHandler.java
  project/src/main/java/com/sist/global/error/dto/ErrorResponse.java
  project/src/main/java/com/sist/global/error/exception/BaseException.java
  project/src/main/java/com/sist/global/error/exception/ErrorType.java
Labels: ✨ 기능

#25 회원가입 기능 추가
  project/src/main/java/com/sist/controller/MemberController.java
  project/src/main/java/com/sist/exception/member/DuplicateEmailException.java
  project/src/main/java/com/sist/exception/member/DuplicateNicknameException.java
  project/src/main/java/com/sist/global/security/config/SecurityConfig.java
  project/src/main/java/com/sist/mapper/MemberMapper.java
  project/src/main/java/com/sist/service/MemberService.java
  project/src/main/webapp/WEB-INF/config/root-context.xml
  project/src/main/webapp/WEB-INF/mapper/config/mapper-config.xml
  project/src/main/webapp/WEB-INF/mapper/member-mapper.xml
Labels: ✨ 기능

#27 송상은 커뮤니티
  project/src/main/java/com/sist/controller/CommunityController.java
  project/src/main/java/com/sist/controller/CommunityRestController.java
  project/src/main/java/com/sist/mapper/CommunityMapper.java
  project/src/main/java/com/sist/service/CommunityService.java
  project/src/main/java/com/sist/vo/CommunityVO.java
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
Labels: ✨ 기능

#28 place_list추가
  project/src/main/java/com/sist/controller/PlaceController.java
  project/src/main/java/com/sist/mapper/PlaceMapper.java
  project/src/main/java/com/sist/service/PlaceService.java
  project/src/main/java/com/sist/vo/PlaceVO.java
  project/src/main/java/com/sist/vo/PlacejjimVO.java
  project/src/main/webapp/resources/templates/fragments/header.jsp
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/place/place_list.jsp
Labels: ✨ 기능

#29 로그인 기능 추가
  project/pom.xml
  project/src/main/java/com/sist/global/error/exception/ErrorType.java
  project/src/main/java/com/sist/global/security/config/SecurityConfig.java
  project/src/main/java/com/sist/global/security/handler/LoginFailureHandler.java
  project/src/main/java/com/sist/global/security/service/UserDetailsServiceImpl.java
  project/src/main/java/com/sist/global/security/vo/AuthMemberVO.java
  project/src/main/webapp/resources/templates/fragments/header.jsp
  project/src/main/webapp/resources/templates/member/login.jsp
Labels: ✨ 기능

#32 Place_list 수정
  project/src/main/java/com/sist/controller/PlaceController.java
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/place/place_list.jsp
Labels: ✨ 기능

#33 고객센터
  project/src/main/java/com/sist/controller/CustomerController.java
  project/src/main/java/com/sist/controller/CustomerRestController.java
  project/src/main/java/com/sist/mapper/CustomerMapper.java
  project/src/main/java/com/sist/service/CustomerService.java
  project/src/main/java/com/sist/vo/CustomerReplyVO.java
  project/src/main/java/com/sist/vo/CustomerVO.java
  project/src/main/java/com/sist/vo/FaqVO.java
  project/src/main/webapp/insert.jsp
  project/src/main/webapp/resources/templates/customer/ask.jsp
  project/src/main/webapp/resources/templates/customer/board.jsp
  project/src/main/webapp/resources/templates/customer/delete.jsp
  project/src/main/webapp/resources/templates/customer/detail.jsp
  project/src/main/webapp/resources/templates/customer/faq.jsp
  project/src/main/webapp/resources/templates/customer/insert.jsp
  project/src/main/webapp/resources/templates/customer/list.jsp
  project/src/main/webapp/resources/templates/customer/update.jsp
Labels: ✨ 기능, 🖥️ UI

#34 고객센터 페이지추가
  project/src/main/java/com/sist/controller/CustomerController.java
  project/src/main/java/com/sist/mapper/CustomerMapper.java
  project/src/main/webapp/resources/templates/customer/list.jsp
  project/src/main/webapp/resources/templates/fragments/header.jsp
Labels: 🖥️ UI

#35 송상은 커뮤니티 insert
  project/pom.xml
  project/src/main/java/com/sist/controller/CommunityController.java
  project/src/main/java/com/sist/controller/CommunityRestController.java
  project/src/main/java/com/sist/mapper/CommunityMapper.java
  project/src/main/java/com/sist/service/CommunityService.java
  project/src/main/java/com/sist/vo/CommunityVO.java
  project/src/main/webapp/WEB-INF/config/servlet-context.xml
  project/src/main/webapp/WEB-INF/web.xml
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/insert_ok.jsp
Labels: ✨ 기능

#38 고객센터
  project/src/main/java/com/sist/controller/CustomerController.java
  project/src/main/java/com/sist/controller/CustomerRestController.java
  project/src/main/java/com/sist/mapper/CustomerMapper.java
  project/src/main/java/com/sist/service/CustomerService.java
  project/src/main/java/com/sist/vo/CustomerVO.java
  project/src/main/webapp/resources/templates/customer/insert.jsp
  project/src/main/webapp/resources/templates/customer/insert_ok.jsp
  project/src/main/webapp/resources/templates/customer/list.jsp
Labels: ✨ 기능, 🖥️ UI

#41 상은 공지사항과 커뮤니티
  project/pom.xml
  project/src/main/java/com/sist/controller/CommunityRestController.java
  project/src/main/java/com/sist/controller/NoticeController.java
  project/src/main/java/com/sist/controller/NoticeRestController.java
  project/src/main/java/com/sist/mapper/CommunityMapper.java
  project/src/main/java/com/sist/mapper/CustomerMapper.java
  project/src/main/java/com/sist/mapper/NoticeMapper.java
  project/src/main/java/com/sist/service/NoticeService.java
  project/src/main/java/com/sist/vo/CommunityVO.java
  project/src/main/java/com/sist/vo/NoticeVO.java
  project/src/main/webapp/resources/templates/community/delete.jsp
  project/src/main/webapp/resources/templates/community/detail.jsp
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
  project/src/main/webapp/resources/templates/community/update.jsp
  project/src/main/webapp/resources/templates/fragments/header.jsp
  project/src/main/webapp/resources/templates/notice/delete.jsp
  project/src/main/webapp/resources/templates/notice/detail.jsp
  project/src/main/webapp/resources/templates/notice/insert.jsp
  project/src/main/webapp/resources/templates/notice/list.jsp
  project/src/main/webapp/resources/templates/notice/update.jsp
Labels: 🖥️ UI

#43 마이 페이지 추가
  project/pom.xml
  project/src/main/java/com/sist/controller/MemberController.java
  project/src/main/java/com/sist/exception/member/NotFoundMemberException.java
  project/src/main/java/com/sist/global/error/exception/ErrorType.java
  project/src/main/java/com/sist/global/security/annotation/LoginMember.java
  project/src/main/java/com/sist/global/security/config/SecurityConfig.java
  project/src/main/java/com/sist/mapper/PlaceMapper.java
  project/src/main/java/com/sist/service/MemberService.java
  project/src/main/java/com/sist/service/PlaceService.java
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/java/com/sist/vo/PlaceReviewVO.java
  project/src/main/java/com/sist/vo/PlacejjimVO.java
  project/src/main/webapp/resources/static/image/no-jjim.png
  project/src/main/webapp/resources/templates/member/login.jsp
  project/src/main/webapp/resources/templates/member/mypage-bookmark.jsp
  project/src/main/webapp/resources/templates/member/mypage-comment.jsp
  project/src/main/webapp/resources/templates/member/mypage-write.jsp
Labels: ✨ 기능, 🖥️ UI

#46 상은 수정
  project/src/main/java/com/sist/controller/CommunityController.java
  project/src/main/java/com/sist/controller/CommunityRestController.java
  project/src/main/java/com/sist/controller/NoticeController.java
  project/src/main/java/com/sist/vo/CommunityReplyVO.java
  project/src/main/java/com/sist/vo/CommunityVO.java
  project/src/main/webapp/resources/templates/community/detail.jsp
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
  project/src/main/webapp/resources/templates/fragments/header.jsp
  project/src/main/webapp/resources/templates/notice/delete.jsp
  project/src/main/webapp/resources/templates/notice/detail.jsp
  project/src/main/webapp/resources/templates/notice/insert.jsp
  project/src/main/webapp/resources/templates/notice/list.jsp
  project/src/main/webapp/resources/templates/notice/update.jsp
Labels: ✨ 기능, 🖥️ UI

#47 무한스크롤, 상세, 검색, 최신순, 조회순 정렬 추가
  project/src/main/java/com/sist/controller/PlaceController.java
  project/src/main/java/com/sist/mapper/PlaceMapper.java
  project/src/main/java/com/sist/service/PlaceService.java
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/place/place_list.jsp
Labels: ✨ 기능

#48 리뷰기능작업
  project/src/main/java/com/sist/controller/ReviewRestController.java
  project/src/main/java/com/sist/mapper/ReviewMapper.java
  project/src/main/java/com/sist/service/ReviewService.java
  project/src/main/java/com/sist/vo/ReviewVO.java
  project/src/main/webapp/resources/templates/besttip/list.jsp
  project/src/main/webapp/resources/templates/review/review_insert.jsp
Labels: 🖥️ UI

#49 상은
  project/src/main/java/com/sist/controller/CommunityController.java
  project/src/main/java/com/sist/controller/CommunityRestController.java
  project/src/main/java/com/sist/controller/NoticeController.java
  project/src/main/java/com/sist/controller/NoticeRestController.java
  project/src/main/java/com/sist/mapper/CommunityMapper.java
  project/src/main/java/com/sist/mapper/NoticeMapper.java
  project/src/main/java/com/sist/service/CommunityService.java
  project/src/main/java/com/sist/service/NoticeService.java
  project/src/main/java/com/sist/vo/CommunityReplyVO.java
  project/src/main/webapp/resources/templates/community/detail.jsp
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
  project/src/main/webapp/resources/templates/community/update.jsp
  project/src/main/webapp/resources/templates/notice/delete.jsp
  project/src/main/webapp/resources/templates/notice/detail.jsp
  project/src/main/webapp/resources/templates/notice/list.jsp
  project/src/main/webapp/test.jsp
Labels: ✨ 기능

#50 망한 리뷰작업
  project/src/main/webapp/resources/templates/index.jsp
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/review/review_delete.jsp
  project/src/main/webapp/resources/templates/review/review_detail.jsp
  project/src/main/webapp/resources/templates/review/review_insert.jsp
  project/src/main/webapp/resources/templates/review/review_list.jsp
  project/src/main/webapp/resources/templates/review/review_update.jsp
Labels: ✨ 기능, 🖥️ UI

#51 고객센터(페이지네이션,수정/삭제 완성)
  project/src/main/java/com/sist/controller/CustomerController.java
  project/src/main/java/com/sist/controller/CustomerRestController.java
  project/src/main/java/com/sist/mapper/CustomerMapper.java
  project/src/main/java/com/sist/service/CustomerService.java
  project/src/main/webapp/resources/templates/customer/detail.jsp
  project/src/main/webapp/resources/templates/customer/faq.jsp
  project/src/main/webapp/resources/templates/customer/insert.jsp
  project/src/main/webapp/resources/templates/customer/list.jsp
  project/src/main/webapp/resources/templates/customer/update.jsp
Labels: ✨ 기능, 🖥️ UI

#52 찜 controller, mapper, service 추가, 오류 수정
  project/src/main/java/com/sist/controller/PlaceController.java
  project/src/main/java/com/sist/mapper/PlaceMapper.java
  project/src/main/java/com/sist/service/PlaceService.java
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/place/place_list.jsp
Labels: ✨ 기능

#53 css 수정
  project/src/main/java/com/sist/controller/PlaceController.java
  project/src/main/webapp/resources/templates/place/place_detail.jsp
  project/src/main/webapp/resources/templates/place/place_list.jsp
Labels: 🖥️ UI

#54 상은 커뮤니티&공지사항
  project/src/main/webapp/resources/static/image/community.jpg
  project/src/main/webapp/resources/static/image/toptop.png
  project/src/main/webapp/resources/static/image/toptoptop.png
  project/src/main/webapp/resources/static/image/toptoptoptop.jpg
  project/src/main/webapp/resources/templates/community/detail.jsp
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
  project/src/main/webapp/resources/templates/notice/insert.jsp
  project/src/main/webapp/resources/templates/notice/list.jsp
Labels: ✨ 기능

#55 상은
  project/src/main/webapp/resources/templates/community/insert.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
  project/src/main/webapp/resources/templates/notice/insert.jsp
  project/src/main/webapp/resources/templates/notice/list.jsp
Labels: ✨ 기능

#56 고객센터 관련 상단 수정
  project/src/main/webapp/resources/templates/customer/delete.jsp
  project/src/main/webapp/resources/templates/customer/detail.jsp
  project/src/main/webapp/resources/templates/customer/faq.jsp
  project/src/main/webapp/resources/templates/customer/insert.jsp
  project/src/main/webapp/resources/templates/customer/list.jsp
  project/src/main/webapp/resources/templates/customer/update.jsp
Labels: 🖥️ UI

#59 끝
  project/src/main/webapp/resources/templates/community/detail.jsp
  project/src/main/webapp/resources/templates/community/list.jsp
Labels: ✨ 기능
